In [1]:
# Common to All
import numpy as np

A = np.array([[1, 2, -10, 4], [3, 4, 5, -6], [3, 3, -2, 5]])
B = np.array([3, 3, 4, 2])
print("A: ", A)
print("B: ", B)

A:  [[  1   2 -10   4]
 [  3   4   5  -6]
 [  3   3  -2   5]]
B:  [3 3 4 2]


In [2]:
# Q2. Finding the Largest Dimension
def length(matrix):
    return max(matrix.shape)

lengthA = length(A)
lengthB = length(B)

print("lengthA: ", lengthA)
print("lengthB: ", lengthB)
print("A.shape: ", A.shape)  # Gives the order of the matrix

lengthA:  4
lengthB:  4
A.shape:  (3, 4)


In [3]:
# Q3: Add the vector B as the fourth row of the matrix A and save the result as a new matrix C.
C = np.vstack((A, B))  # Vertically stacks/combine row-wise
print("C: ", C)

C:  [[  1   2 -10   4]
 [  3   4   5  -6]
 [  3   3  -2   5]
 [  3   3   4   2]]


In [4]:
# Q4: Create a new matrix D whose entries are located in the rows 2, 3, 4 and columns 3, 4 of the matrix C.
D = C[1:4, 2:4]
print("D: ", D)


D:  [[ 5 -6]
 [-2  5]
 [ 4  2]]


In [5]:
# Q5: Create a transpose of the matrix D and save the transposed matrix as the matrix E.
E = D.T
print("E: ", E)

E:  [[ 5 -2  4]
 [-6  5  2]]


In [6]:
# Q6: Check the size of the matrix E and store the result of this operation as two variables m, n.
m, n = E.shape
print("m: ", m)
print("n: ", n)

m:  2
n:  3


In [7]:
# Q7: Python allows for the creation of equally spaced vectors which can be useful in many situations.
EqualSpaced = np.arange(0, 2 * np.pi, np.pi / 10)
EqualSpaced1 = np.linspace(0, 2 * np.pi, 21)
print("EqualSpaced: ", EqualSpaced)
print("EqualSpaced1: ", EqualSpaced1)

EqualSpaced:  [0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265 3.45575192
 3.76991118 4.08407045 4.39822972 4.71238898 5.02654825 5.34070751
 5.65486678 5.96902604]
EqualSpaced1:  [0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265 3.45575192
 3.76991118 4.08407045 4.39822972 4.71238898 5.02654825 5.34070751
 5.65486678 5.96902604 6.28318531]


In [8]:
# Q8: Find the maximal and minimal elements in each of the columns of the matrix A.
maxcolA = np.max(A, axis=0)
mincolA = np.min(A, axis=0)
print("maxcolA: ", maxcolA)
print("mincolA: ", mincolA)

maxcolA:  [3 4 5 5]
mincolA:  [  1   2 -10  -6]


In [9]:
# Q9: Find the maximal and minimal elements in each row of the matrix A.
maxrowA = np.max(A, axis=1)
minrowA = np.min(A, axis=1)

In [10]:
# Find the maximum and minimum elements in the entire matrix A
maxA = np.max(A)
minA = np.min(A)
print("maxrowA: ", maxrowA)
print("minrowA: ", minrowA)
print("maxA: ", maxA)
print("minA: ", minA)

maxrowA:  [4 5 5]
minrowA:  [-10  -6  -2]
maxA:  5
minA:  -10


In [11]:
# Q10: Repeat the last two steps using the commands mean and sum instead of max and min.
meancolA = np.mean(A, axis=0)
meanrowA = np.mean(A, axis=1)
sumcolA = np.sum(A, axis=0)
sumrowA = np.sum(A, axis=1)

# Calculate mean and sum of all elements in A
meanA = np.mean(A)
sumA = np.sum(A)
print("meancolA: ", meancolA)
print("meanrowA: ", meanrowA)
print("sumcolA: ", sumcolA)
print("sumrowA: ", sumrowA)
print("meanA: ", meanA)
print("sumA: ", sumA)

meancolA:  [ 2.33333333  3.         -2.33333333  1.        ]
meanrowA:  [-0.75  1.5   2.25]
sumcolA:  [ 7  9 -7  3]
sumrowA:  [-3  6  9]
meanA:  1.0
sumA:  12


In [12]:
# Q11: Create two matrices F and G with random integer entries from −4 to 4.
F = np.random.randint(-4, 5, (5, 3))
G = np.random.randint(-4, 5, (5, 3))
print("F: ", F)
print("G: ", G)

F:  [[-1 -3  2]
 [ 3 -4  0]
 [ 1  2  2]
 [ 1  1  4]
 [ 2 -1  2]]
G:  [[ 4 -2 -1]
 [-2 -2  1]
 [ 2 -2  3]
 [-4  2  3]
 [ 1 -3  2]]


In [13]:
# Q12: Perform the operations 0.4*F, F+G, F-G, F.*G, storing the results in ScMultF, SumFG, DiffFG, and ElProdFG respectively.
ScMultF = 0.4 * F
SumFG = F + G
DiffFG = F - G
ElProdFG = F * G
print("ScMultF: ", ScMultF)
print("SumFG: ", SumFG)
print("DiffFG: ", DiffFG)
print("ElProdFG: ", ElProdFG)

ScMultF:  [[-0.4 -1.2  0.8]
 [ 1.2 -1.6  0. ]
 [ 0.4  0.8  0.8]
 [ 0.4  0.4  1.6]
 [ 0.8 -0.4  0.8]]
SumFG:  [[ 3 -5  1]
 [ 1 -6  1]
 [ 3  0  5]
 [-3  3  7]
 [ 3 -4  4]]
DiffFG:  [[-5 -1  3]
 [ 5 -2 -1]
 [-1  4 -1]
 [ 5 -1  1]
 [ 1  2  0]]
ElProdFG:  [[-4  6 -2]
 [-6  8  0]
 [ 2 -4  6]
 [-4  2 12]
 [ 2  3  4]]


In [14]:
# Q13: Check the size of the matrix F and the size of A, storing the results in the variables sizeF and sizeA, respectively.
sizeF = F.shape
sizeA = A.shape
print("sizeF: ", sizeF)
print("sizeA: ", sizeA)

sizeF:  (5, 3)
sizeA:  (3, 4)


In [15]:
# Q14: Can we matrix-multiply F and A? Explain.
if sizeF[1] == sizeA[0]:
    H = F @ A
    print("H: ", H)
else:
    print("Cannot multiply F and A due to incompatible dimensions.")

H:  [[ -4  -8  -9  24]
 [ -9 -10 -50  36]
 [ 13  16  -4   2]
 [ 16  18 -13  18]
 [  5   6 -29  24]]


In [16]:
# Q15: Generate the identity matrix eye33 with 3 rows and 3 columns using the np.eye() function.
eye33 = np.eye(3)
print("eye33: ", eye33)

eye33:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
# Q16: Run the commands to generate matrices of zeros with size 5x3 and ones with size 4x2.
zeros53 = np.zeros((5, 3))
ones42 = np.ones((4, 2))
print("zeros53: ", zeros53)
print("ones42: ", ones42)

zeros53:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones42:  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
# Q17: Generate the diagonal 3x3 matrix S with the diagonal elements {1, 2, 7} using the np.diag() function.
S = np.diag([1, 2, 7])
print("S: ", S)

S:  [[1 0 0]
 [0 2 0]
 [0 0 7]]


In [19]:
# Q18: Extract the diagonal elements from a random 6x6 matrix and save them in a separate vector.
R = np.random.rand(6, 6)
diagR = np.diag(R)
print("R: ", R)
print("diagR: ", diagR)

R:  [[0.82533273 0.83447603 0.17383619 0.96055078 0.04001079 0.1857575 ]
 [0.89227326 0.49393464 0.21153101 0.87491871 0.15035792 0.12126578]
 [0.72830601 0.96742163 0.82895086 0.4656662  0.99011151 0.47383155]
 [0.11023276 0.08289951 0.98131245 0.14597405 0.63223002 0.31845077]
 [0.01792146 0.97398179 0.89618967 0.16602586 0.71727053 0.70510433]
 [0.60514504 0.49251959 0.93947064 0.45362529 0.39608687 0.59904552]]
diagR:  [0.82533273 0.49393464 0.82895086 0.14597405 0.71727053 0.59904552]


In [20]:
# Q19: Create a sparse diagonal matrix using diags and convert it to a dense matrix.
from scipy.sparse import diags
diag121 = diags([-np.ones(10), 2*np.ones(10), -np.ones(10)], [-1, 0, 1], shape=(10, 10)).todense()
print("diag121: ", diag121)

diag121:  [[ 2. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  2. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  2.]]
