In [1]:
#Q1.  Create a new cell and type in the following commands to generate the matrix A and the column vector b

import numpy as np
# Define a function to create a magic-like matrix
def create_magic_like(n):
    magic_square = np.zeros((n, n), dtype=int)
    row, col = 0, n // 2
    num = 1

    while num <= n * n:
        magic_square[row, col] = num
        num += 1
        new_row, new_col = (row - 1) % n, (col + 1) % n

        if magic_square[new_row, new_col]:
            row += 1
        else:
            row, col = new_row, new_col

    return magic_square

# Generate a 5x5 "magic-like" matrix
A = create_magic_like(5)

# Define column vector b
b = np.array([10, 26, 42, 59, 38])

# Print matrix A and vector b
print("Matrix A:")
print(A)
print("\nVector b:", b)

Matrix A:
[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]

Vector b: [10 26 42 59 38]


In [2]:
#Q2. Use the Python’s “numpy” solver
x = np.linalg.solve(A, b)
# Print the solution vector x
print("\nSolution vector x:")
print(x)


Solution vector x:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]


In [3]:
#Q3. Check how accurate the solution

r = np.dot(A, x) - b
# Print the residual vector r
print("\nResidual vector r:")
print(r)

# resulting vector r should be very close to zero


Residual vector r:
[ 0.00000000e+00  3.55271368e-15  0.00000000e+00  0.00000000e+00
 -7.10542736e-15]


In [4]:
#Q4. Explain how LU decomposition can be used to solve the linear system 𝐴𝑥=𝑏 and provide a Python function to compute the solution using SciPy.

import scipy.linalg 
# Perform LU decomposition of A
P, L, U = scipy.linalg.lu(A) # Note: Use scipy.linalg.lu for LU decomposition
# Solve the system Ax = b using LU decomposition
x1 = np.linalg.solve(A, b)
# Calculate the error between solutions
err1 = np.dot(A, x1) - b
# Print matrices P, L, U and vectors x1, err1
print("Matrix P (Permutation matrix):")
print(P)
print("\nMatrix L (Lower triangular matrix):")
print(L)
print("\nMatrix U (Upper triangular matrix):")
print(U)
print("\nSolution vector x1:")
print(x1)
print("\nError vector err1:")
print(err1)

Matrix P (Permutation matrix):
[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

Matrix L (Lower triangular matrix):
[[1.         0.         0.         0.         0.        ]
 [0.73913043 1.         0.         0.         0.        ]
 [0.47826087 0.76873662 1.         0.         0.        ]
 [0.17391304 0.25267666 0.5163652  1.         0.        ]
 [0.43478261 0.48394004 0.72308355 0.92307692 1.        ]]

Matrix U (Upper triangular matrix):
[[ 23.           5.           7.          14.          16.        ]
 [  0.          20.30434783  -4.17391304  -2.34782609   3.17391304]
 [  0.           0.          24.8608137   -2.89079229  -1.09207709]
 [  0.           0.           0.          19.65116279  18.97932817]
 [  0.           0.           0.           0.         -22.22222222]]

Solution vector x1:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]

Error vector err1:
[ 0.00000000e+00  3.55271368e-15  0.00000000e+00  0.00000000e+00
 -7.

In [5]:
#Q5. Function to solve linear systems of the type yA = b.

y = np.linalg.lstsq(A, b, rcond=None)[0]
# Print the solution vector y
print("\nSolution vector y:")
print(y)


Solution vector y:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]


In [9]:
#Q6.Use the inverse matrix to solve the same system of linear equations

# Solve the system Ax = b using matrix inverse
A_inv = np.linalg.inv(A)
x2 = np.dot(A_inv, b)
# Calculate the residual r2 and error err2
r2 = np.dot(A, x2) - b
err2 = x - x2
# Print solution vector x2, residual r2 and error err2
print("\nSolution vector x2 using inverse:")
print(x2)
print("\nResidual vector r2:")
print(r2)
print("\nError vector err2:")
print(err2)


Solution vector x2 using inverse:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]

Residual vector r2:
[-3.55271368e-15 -3.55271368e-15 -7.10542736e-15  0.00000000e+00
 -7.10542736e-15]

Error vector err2:
[-7.63278329e-17  4.16333634e-17  0.00000000e+00  4.44089210e-16
  5.55111512e-17]


In [10]:
#Q7. Reduced row echelon form
import numpy as np

def rref(A):
    """
    Computes the reduced row echelon form (RREF) of a matrix A.

    Parameters:
    A : numpy.ndarray
        Input matrix of shape (m, n)

    Returns:
    R : numpy.ndarray
        Reduced row echelon form of matrix A
    """
    A = A.astype(float)
    m, n = A.shape
    lead = 0

    for r in range(m):
        if lead >= n:
            break
        if A[r, lead] == 0:
            for i in range(r + 1, m):
                if A[i, lead] != 0:
                    A[[r, i]] = A[[i, r]]
                    break
        if A[r, lead] != 0:
            A[r] = A[r] / A[r, lead]
            for i in range(m):
                if i != r:
                    A[i] -= A[i, lead] * A[r]
        lead += 1

    return A

# Define matrix A and vector b
A = np.array([[17, 24, 1], [23, 5, 7], [4, 6, 8]])
b = np.array([10, 26, 42])

# Compute reduced row echelon form of [A | b]
C = np.hstack((A, b[:, np.newaxis]))
R = rref(C)

# Extract solution vector x3 from the RREF matrix
x3 = R[:, -1]

# Calculate residuals
r3 = np.dot(A, x3) - b
err3 = x3  # Assuming `x` is not defined, using x3 itself

# Print results
print("\nSolution vector x3 (from RREF):")
print(x3)
print("\nResidual vector r3 (from RREF):")
print(r3)
print("\nError vector err3 (difference between x and x3):")
print(err3)



Solution vector x3 (from RREF):
[-0.54371585  0.59016393  5.07923497]

Residual vector r3 (from RREF):
[-7.10542736e-15  0.00000000e+00  0.00000000e+00]

Error vector err3 (difference between x and x3):
[-0.54371585  0.59016393  5.07923497]


In [12]:
#Q8.Compare the computational efficiency of all three methods, run the code cell:

import numpy as np
import time

def rref(A):
    """
    Computes the reduced row echelon form (RREF) of a matrix A.

    Parameters:
    A : numpy.ndarray
        Input matrix of shape (m, n)

    Returns:
    R : numpy.ndarray
        Reduced row echelon form of matrix A
    """
    A = A.astype(float)
    m, n = A.shape
    lead = 0

    for r in range(m):
        if lead >= n:
            break
        if A[r, lead] == 0:
            for i in range(r + 1, m):
                if A[i, lead] != 0:
                    A[[r, i]] = A[[i, r]]
                    break
        if A[r, lead] != 0:
            A[r] = A[r] / A[r, lead]
            for i in range(m):
                if i != r:
                    A[i] -= A[i, lead] * A[r]
        lead += 1

    return A

# Initialize Num
Num = 500

# Generate matrix A and vector b
A = np.random.rand(Num, Num) + Num * np.eye(Num)
b = np.random.rand(Num, 1)

# Method 1: Solve using backslash operator (NumPy solve)
start_time = time.time()
x1 = np.linalg.solve(A, b)
end_time = time.time()
time_backslash = end_time - start_time

# Method 2: Solve using matrix inverse
start_time = time.time()
x2 = np.linalg.inv(A) @ b
end_time = time.time()
time_inv = end_time - start_time

# Method 3: Solve using reduced row echelon form (RREF)
start_time = time.time()
C = np.hstack((A, b))
R = rref(C)
x3 = R[:, -1]
end_time = time.time()
time_rref = end_time - start_time

# Print the solution vectors and computational times
print("\nSolution vector x1 (using backslash operator):")
print(x1)

print("\nSolution vector x2 (using matrix inverse):")
print(x2)

print("\nSolution vector x3 (using reduced row echelon form):")
print(x3)

print("\nComputational times:")
print(f"Backslash operator: {time_backslash:.6f} seconds")
print(f"Matrix inverse: {time_inv:.6f} seconds")
print(f"Reduced row echelon form (rref): {time_rref:.6f} seconds")


Solution vector x1 (using backslash operator):
[[ 1.38482270e-03]
 [ 6.09857810e-04]
 [ 1.02532375e-04]
 [ 2.53908111e-04]
 [-6.02497068e-05]
 [ 9.16585600e-05]
 [ 2.62488631e-04]
 [ 5.31966596e-04]
 [ 6.44823946e-04]
 [ 7.05956130e-04]
 [ 4.47403814e-05]
 [ 3.81037719e-04]
 [ 6.49905692e-04]
 [-2.66784599e-04]
 [ 1.65869576e-03]
 [ 1.62662343e-03]
 [ 1.71805969e-04]
 [ 1.41499011e-03]
 [ 7.38717105e-04]
 [ 5.73389843e-04]
 [ 1.65229551e-03]
 [ 1.46576140e-03]
 [ 8.37425178e-04]
 [ 9.32249705e-04]
 [-1.53268991e-04]
 [ 5.49779014e-04]
 [ 2.95482643e-04]
 [ 1.46340206e-03]
 [ 7.44699218e-04]
 [ 1.33880251e-03]
 [ 7.63323233e-04]
 [ 4.11072049e-04]
 [-7.77494141e-05]
 [ 4.40498330e-05]
 [ 2.37482362e-04]
 [ 1.67363212e-03]
 [ 1.46794086e-03]
 [ 5.78426645e-04]
 [ 1.47594544e-04]
 [-4.88432486e-05]
 [ 5.31554753e-04]
 [ 1.67689324e-03]
 [ 1.59888864e-03]
 [ 9.48802700e-04]
 [-2.55179686e-04]
 [ 7.96966923e-04]
 [ 1.07531229e-03]
 [ 1.12513925e-03]
 [ 8.97599920e-04]
 [ 5.84712784e-05]
 [

In [13]:
#Q9. Use Python to solve rectangular systems of linear equations. Use the Python backslash operator
import numpy as np

# Define matrix A and vector b for the overdetermined system
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10],
              [9, 11, 12]])

b = np.array([1, 2, 3, 4]).reshape(-1, 1)  # Reshape b to be a column vector

# Solve the system Ax = b using the least squares method
x = np.linalg.lstsq(A, b, rcond=None)[0]

# Calculate the residual r = Ax - b
r = np.dot(A, x) - b

# Print the solution vector x
print("\nSolution vector x:")
print(x)

# Print the residual vector r
print("\nResidual vector r:")
print(r)

# Solve using normal equations
ATA_inv = np.linalg.inv(np.dot(A.T, A))  # Compute (A.T * A)^(-1)
ATb = np.dot(A.T, b)  # Compute A.T * b
y = np.dot(ATA_inv, ATb)  # Solve normal equations A.T * A * y = A.T * b

# Calculate the difference between x and y
err = x - y

# Print the solution vector y from normal equations
print("\nSolution vector y (from normal equations):")
print(y)

# Print the difference vector err (should be close to zero)
print("\nDifference vector err (x - y):")
print(err)


Solution vector x:
[[-0.24630542]
 [ 0.38916256]
 [ 0.16256158]]

Residual vector r:
[[ 0.01970443]
 [-0.06403941]
 [ 0.01477833]
 [ 0.01477833]]

Solution vector y (from normal equations):
[[-0.24630542]
 [ 0.38916256]
 [ 0.16256158]]

Difference vector err (x - y):
[[-1.13797860e-15]
 [-3.75255382e-14]
 [ 1.19071419e-14]]


In [18]:
#Q10 a. Case of an underdetermined system. If this system is consistent then it has an infinite number of solutions.

import numpy as np

# Define matrix A (4x3)
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

# Define vector b (must have 4 elements to match rows of A)
b = np.array([1, 3, 5, 7]).reshape(-1, 1)  # Reshaped to (4x1)

# Solve the system Ax = b using the least squares method
x = np.linalg.lstsq(A, b, rcond=None)[0]

# Calculate the residual r1 = Ax - b
r1 = np.dot(A, x) - b

# Print the solution vector x
print("\nSolution vector x:")
print(x)

# Print the residual vector r1
print("\nResidual vector r1:")
print(r1)


Solution vector x:
[[0.38888889]
 [0.22222222]
 [0.05555556]]

Residual vector r1:
[[8.8817842e-16]
 [8.8817842e-16]
 [8.8817842e-16]
 [0.0000000e+00]]


In [19]:
#10b. Alternative Solution Using the Pseudoinverse

# Compute pseudoinverse of A
A_pinv = np.linalg.pinv(A)

# Compute another solution using the pseudoinverse
y = np.dot(A_pinv, b)

# Calculate the residual r2 = Ax - b for solution y
r2 = np.dot(A, y) - b

# Print the solution vector y from pseudoinverse
print("\nSolution vector y (from pseudoinverse):")
print(y)

# Print the residual vector r2
print("\nResidual vector r2:")
print(r2)


Solution vector y (from pseudoinverse):
[[0.38888889]
 [0.22222222]
 [0.05555556]]

Residual vector r2:
[[ 1.55431223e-15]
 [-4.44089210e-16]
 [-2.66453526e-15]
 [-4.44089210e-15]]


In [21]:
#10c. Complete Solution Using Null Space

import numpy as np
from scipy.linalg import null_space

# Define matrix A (4x3)
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

# Define vector b (4x1)
b = np.array([1, 3, 5, 7]).reshape(-1, 1)

# Solve the system Ax = b using least squares
x = np.linalg.lstsq(A, b, rcond=None)[0]

# Compute the null space of A
null_space_A = null_space(A)

# Check null_space_A shape before proceeding
print(f"Null space shape: {null_space_A.shape}")  # Expected to be (3, 1)

# Choose a scalar C instead of a vector
C = np.array([1])  # Must match the number of columns in null_space_A

# Compute the complete solution z = null_space(A) * C + x
z = np.dot(null_space_A, C) + x

# Print the complete solution vector z
print("\nComplete solution vector z:")
print(z)

Null space shape: (3, 1)

Complete solution vector z:
[[-0.0193594   1.20538547 -0.0193594 ]
 [-0.18602607  1.0387188  -0.18602607]
 [-0.35269273  0.87205214 -0.35269273]]
