## Project 5: Systems of linear equations and college football team ranking (with an example of the Big 12)

In [1]:
#Q1.Load both matrices into your Python script using the load command:

import numpy as np
from scipy.io import loadmat
# Load the matrices from .mat files
data_scores = loadmat(r"C:\admin\2nd year\sem4\La\projects\p5\Scores.mat")
data_differentials = loadmat(r"C:\admin\2nd year\sem4\La\projects\p5\Differentials.mat")
# Extract the relevant matrices
Scores = data_scores['Scores']
Differentials = data_differentials['Differentials']

In [2]:
#Q2. Create the matrix and the right-hand side of Colley’s system of linear equations

# Colley's method 
# Define variables 
games = np.abs(Scores) 
total = np.sum(games, axis=1) 
# Construct Colley's matrix and the right-hand side vector 
ColleyMatrix = 2 * np.eye(10) + np.diag(total) - games 
RightSide = 1 + 0.5 * np.sum(Scores, axis=1)

# Print to verify 
print("ColleyMatrix:\n", ColleyMatrix) 
print("\nRightSide:\n", RightSide)

ColleyMatrix:
 [[11. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. 11. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. 11. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. 11. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. 11. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. 11. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. 11. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. 11. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. 11. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. 11.]]

RightSide:
 [-0.5 -1.5 -2.5  2.5  5.5  3.5  0.5 -0.5 -0.5  2.5]


In [3]:
#Q3. Solve the linear system using the backslash operator:

RanksColley = np.linalg.solve(ColleyMatrix, RightSide)
print("RanksColley:\n", RanksColley)

RanksColley:
 [0.33333333 0.25       0.16666667 0.58333333 0.83333333 0.66666667
 0.41666667 0.33333333 0.33333333 0.58333333]


In [4]:
#Q4. Display the results on the screen

# Teams list
Teams = [
    'Baylor', 'Iowa State', 'University of Kansas', 'Kansas State',
    'University of Oklahoma', 'Oklahoma State', 'Texas Christian',
    'University of Texas Austin', 'Texas Tech', 'West Virginia'
]

# Sort the ranks in descending order and get the order of indices
Order = np.argsort(RanksColley)[::-1]
RanksDescend = RanksColley[Order]

# Display the results
print('\nColley Rankings:')
for j in range(10):
    print(f'{RanksColley[Order[j]]:8.3f} {Teams[Order[j]]:15s}')


Colley Rankings:
   0.833 University of Oklahoma
   0.667 Oklahoma State 
   0.583 Kansas State   
   0.583 West Virginia  
   0.417 Texas Christian
   0.333 Baylor         
   0.333 Texas Tech     
   0.333 University of Texas Austin
   0.250 Iowa State     
   0.167 University of Kansas


In [5]:
#Q5. Construct the matrix P and right-hand side B for Massey’s method

# Massey's method
l = 0
P = []
B = []

# Loop through the upper triangular part of the Differentials matrix
for j in range(9):
    for k in range(j + 1, 10):
        if Differentials[j, k] != 0:
            l += 1
            row = np.zeros(10)
            row[j] = 1
            row[k] = -1
            P.append(row)
            B.append(Differentials[j, k])

# Convert lists to numpy arrays
P = np.array(P)
B = np.array(B)

# Print matrices
print("Matrix P:\n", P)
print("Vector B:\n", B)

Matrix P:
 [[ 1. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0. -1.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0. -1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0. -1.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  1. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  1. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0. -1.  0.]


In [6]:
#Q6. Create the normal system of linear equations

# Create the normal system of linear equations
A = np.dot(P.T, P)
D = np.dot(P.T, B)

# Print matrices
print("Matrix A:\n", A)
print("Vector D:\n", D)

Matrix A:
 [[ 9. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1.  9. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1.  9. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1.  9. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1.  9. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.  9. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.  9. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.  9. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  9. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.  9.]]
Vector D:
 [ -49.  -34. -202.   45.  169.   70.    2.  -25.  -51.   75.]


In [7]:
#Q7. Substitute the last row of the matrix as described above

# Substitute the last row of the matrix and the last element of the vector
A[9, :] = np.ones(10)
D[9] = 0

# Print the updated matrix and vector
print("Updated Matrix A:\n", A)
print("Updated Vector D:\n", D)

Updated Matrix A:
 [[ 9. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1.  9. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1.  9. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1.  9. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1.  9. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.  9. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.  9. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.  9. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  9. -1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
Updated Vector D:
 [ -49.  -34. -202.   45.  169.   70.    2.  -25.  -51.    0.]


In [8]:
#Q8. Finally, solve the system

# Solve the system
RanksMassey = np.linalg.solve(A, D)

# Print the results
print("RanksMassey:\n", RanksMassey)

RanksMassey:
 [ -4.9  -3.4 -20.2   4.5  16.9   7.    0.2  -2.5  -5.1   7.5]


In [9]:
#Q9. Display the results on the screen as before

# Sort the ranks in descending order
Order = np.argsort(RanksMassey)[::-1]
RanksDescend = RanksMassey[Order]

# Print the results
print("\nMassey Rankings:")
for j in range(10):
    print(f'{RanksDescend[j]:8.3f} {Teams[Order[j]]:<15}')


Massey Rankings:
  16.900 University of Oklahoma
   7.500 West Virginia  
   7.000 Oklahoma State 
   4.500 Kansas State   
   0.200 Texas Christian
  -2.500 University of Texas Austin
  -3.400 Iowa State     
  -4.900 Baylor         
  -5.100 Texas Tech     
 -20.200 University of Kansas


In [10]:
#Q10. Switch the result of the game between the top two teams in Colley’s ranking

# Identify the current top two teams according to Colley's rankings
top_teams_colley = sorted(range(len(RanksColley)), key=lambda i: RanksColley[i], reverse=True)[:2]

# Switch the result of the game
Scores[top_teams_colley[0], top_teams_colley[1]] = -Scores[top_teams_colley[0], top_teams_colley[1]]

# Recalculate Colley's rankings
games = np.abs(Scores)
total = np.sum(games, axis=1)
ColleyMatrix = 2 * np.eye(10) + np.diag(total) - games
RightSide = 1 + 0.5 * np.sum(Scores, axis=1)
RanksColley_updated = np.linalg.solve(ColleyMatrix, RightSide)

# Print updated rankings
teams = [
    'Baylor', 'Iowa State', 'University of Kansas', 'Kansas State', 
    'University of Oklahoma', 'Oklahoma State', 'Texas Christian', 
    'University of Texas Austin', 'Texas Tech', 'West Virginia'
] 
Order_updated = np.argsort(RanksColley_updated)[::-1]
print("\nUpdated Colley's Rankings After Game Result Switch:")
for j in range(10):
    print(f"{RanksColley_updated[Order_updated[j]]:8.3f} {Teams[Order_updated[j]]}")

# Reset the game result for future calculations 
Scores[top_teams_colley[0], top_teams_colley[1]] = -Scores[top_teams_colley[0],top_teams_colley[1]] 


Updated Colley's Rankings After Game Result Switch:
   0.708 University of Oklahoma
   0.625 Oklahoma State
   0.542 Kansas State
   0.542 West Virginia
   0.375 Texas Christian
   0.292 Baylor
   0.292 Texas Tech
   0.292 University of Texas Austin
   0.208 Iowa State
   0.125 University of Kansas


In [11]:
#Q11. Switch the result of the game between the top two teams in Massey’s ranking

# Identify the current top two teams according to Massey's rankings
top_teams_massey = sorted(range(len(RanksMassey)), key=lambda i: RanksMassey[i], reverse=True)[:2]

# Adjust the differential matrix for the switched game result
if Differentials[top_teams_massey[0], top_teams_massey[1]] != 0:
    Differentials[top_teams_massey[0], top_teams_massey[1]] = -Differentials[top_teams_massey[0], top_teams_massey[1]]

# Recalculate Massey's rankings
P = np.zeros((45, 10)) 
B = np.zeros(45) 
l = -1

for j in range(9):
    for k in range(j + 1, 10):
        if Differentials[j, k] != 0:
            l += 1 
            P[l, j] = 1 
            P[l, k] = -1 
            B[l] = Differentials[j, k]

P[44, :] = np.ones(10) 
B[44] = 0 
A = np.dot(P.T, P)
D = np.dot(P.T, B)

RanksMassey_updated = np.linalg.solve(A, D)

# Sort the teams based on updated rankings
Order_updated_massey = np.argsort(RanksMassey_updated)[::-1]

# Print updated rankings
print("\nUpdated Massey's Rankings After Game Result Switch:")
for j in range(10):
    print(f"{RanksMassey_updated[Order_updated_massey[j]]:8.3f} {Teams[Order_updated_massey[j]]}")

# Reset the game result for future calculations
if Differentials[top_teams_massey[0], top_teams_massey[1]] != 0: 
    Differentials[top_teams_massey[0], top_teams_massey[1]] = -Differentials[top_teams_massey[0], top_teams_massey[1]]


Updated Massey's Rankings After Game Result Switch:
  11.500 West Virginia
  11.300 University of Oklahoma
   7.000 Oklahoma State
   4.500 Kansas State
   0.200 Texas Christian
  -2.500 University of Texas Austin
  -3.400 Iowa State
  -3.500 Texas Tech
  -4.900 Baylor
 -20.200 University of Kansas
